### PR TITLE
fix: Resource type not visible in Firefox Requestly Devtools

### LINKED ISSUE #1126: bug: Resource type not visible in Firefox Requestly Devtools
### Describe your issue?

Resource Type (XHR, Script, Document ...) is not visible in Firefox Requestly Devtools.

Current
image

Ideal
image

### Repro steps

NA

### What Requestly tool were you using?

- [ ] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOs Ventura 13.0.1, Firefox

### Requestly Version

v23.9.20

### Error screenshot

_No response_

### PR DESCRIPTION
**Pull request by adarsh-sgh**
Fixes #1126 
After this code change whenever a network event comes we will set the `_resourceType` attribute of the event if it's not already set (which is in case of firefox).
Using similar logic that chromium uses to get `_resourceType`. See the `fromMimeType` function [here](https://chromium.googlesource.com/chromium/src.git/+/64.0.3261.1/third_party/WebKit/Source/devtools/front_end/common/ResourceType.js)

## Before the fix
image

## After the fix

image

### CODE REVIEW

**Comment by adarsh-sgh** [comment]
@wrongsahil  @sagarsoni7 This PR implemets the solution as discussed in the issue #1126 
requesting your review on this.

**Comment by adarsh-sgh** [comment]
@wrongsahil @sagarsoni7 can we please get this PR reviewed, this issue is open since more than 1 years.

File: browser-extension/common/src/devtools/utils.ts [hunk 1]
```diff
@@ -112,6 +112,23 @@ export const matchResourceTypeFilter = (
   }
 };
 
+export const getNetworkResourceType = (networkEvent: NetworkEvent) => {
+  const mimeType = networkEvent.response.content.mimeType;
```
Comment (wrongsahil) [inline browser-extension/common/src/devtools/utils.ts:116]:
```suggestion
  const mimeType = networkEvent?.response?.content?.mimeType;
  if(!mimeType) return NetworkResourceType.OTHER;
```

**Review by wrongsahil — CHANGES_REQUESTED** [review]

**Comment by wrongsahil** [comment]
@adarsh-sgh Just one small change. Rest looks good

**Comment by adarsh-sgh** [comment]
> @adarsh-sgh Just one small change. Rest looks good

Done @wrongsahil

**Review by wrongsahil — APPROVED** [review]
This looks good now. LGTM.

Thanks for helping out @adarsh-sgh :D . We're planning to release MV3 version of Firefox this week. Will release this with that
